### ISSUE TITLE
 Is device twin supported in Arduino?

### ISSUE THREAD

**Issue by MehranMazhar** [markrad/Azure-IoT-ESP8266#1]
Hi Mark 
 Is device twin supported in Arduino with ESP8266 ?
if yes how can use twin functionality on ardunio and esp8266 ?

**Comment by markrad** [comment]
Hi @MehranMazhar,

Sorry I must have missed the notification for this comment hence the delay. The device twin functionality is implemented via a different MQTT topic. This code does not currently support it but it shouldn't be too hard to add it. Details about the required implementation can be found here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#using-the-mqtt-protocol-directly. Device Twin functionality did not exist when I implemented this code. Yes it should work on an Arduino based device.
